MvcDynamoAWS/Models/Coche.cs
using Amazon.DynamoDBv2.DataModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcDynamoAWS.Models
{
    [DynamoDBTable("cochesjalt")]
    public class Coche
    {
        [DynamoDBHashKey]
        [DynamoDBProperty("idcoche")]
        public int IdCoche { get; set; }
        [DynamoDBProperty("marca")]
        public String Marca { get; set; }
        [DynamoDBProperty("modelo")]
        public String Modelo { get; set; }
        [DynamoDBProperty("velocidad")]
        public int Velocidad { get; set; }

        [DynamoDBProperty("motor")]
        public Motor Motor { get; set; }
    }

}

MvcDynamoAWS/Models/ErrorViewModel.cs
using System;

namespace MvcDynamoAWS.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcDynamoAWS/Models/Motor.cs
using Amazon.DynamoDBv2.DataModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcDynamoAWS.Models
{
    public class Motor
    {
        [DynamoDBProperty("tipo")]
        public String Tipo { get; set; }

        [DynamoDBProperty("caballos")]
        public int Caballos { get; set; }

        [DynamoDBProperty("cilindrada")]
        public int Cilindrada { get; set; }
    }
}

MvcDynamoAWS/Controllers/CochesController.cs
using Microsoft.AspNetCore.Mvc;
using MvcDynamoAWS.Models;
using MvcDynamoAWS.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcDynamoAWS.Controllers
{
    public class CochesController : Controller
    {
        private ServiceDynamoDB service;

        public CochesController(ServiceDynamoDB service)
        {
            this.service = service;
        }

        public async Task<IActionResult> Index()
        {
            List<Coche> coches = await this.service.GetCochesAsync();
            return View(coches);
        }

        public async Task<IActionResult> Details(int id)
        {
            Coche car = await this.service.FindCocheAsync(id);
            return View(car);
        }

        public async Task<IActionResult> Delete(int id)
        {
            await this.service.DeleteCocheAsync(id);
            return RedirectToAction("Index");
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Coche car, string incluirmotor, string tipo, int cilindrada, int caballos)
        {
            if(incluirmotor != null)
            {
                car.Motor = new Motor();
                car.Motor.Tipo = tipo;
                car.Motor.Cilindrada = cilindrada;
                car.Motor.Caballos = caballos;
            }
            await this.service.CreateCocheAsync(car);
            return RedirectToAction("Index");
        }


        public IActionResult SearchCoches()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SearchCoches(string marca)
        {
            List<Coche> coches = await this.service.SearchCochesAsync(marca);

            return View(coches);
        }
    }

}

MvcDynamoAWS/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MvcDynamoAWS.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MvcDynamoAWS.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcDynamoAWS/Views/Coches/Create.cshtml
@model MvcDynamoAWS.Models.Coche

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Coche</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdCoche" class="control-label"></label>
                <input asp-for="IdCoche" class="form-control" />
                <span asp-validation-for="IdCoche" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Marca" class="control-label"></label>
                <input asp-for="Marca" class="form-control" />
                <span asp-validation-for="Marca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Modelo" class="control-label"></label>
                <input asp-for="Modelo" class="form-control" />
                <span asp-validation-for="Modelo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Velocidad" class="control-label"></label>
                <input asp-for="Velocidad" class="form-control" />
                <span asp-validation-for="Velocidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
            <input type="checkbox" class="form-control" name="incluirmotor" value="true" />
            Incluir Motor <br />
            <label>Tipo Motor: </label>
            <input type="text" name="tipo" class="form-control" /><br />
            <label>Cilindrada: </label>
            <input type="number" name="Cilindrada" class="form-control" /><br />
            <label>Caballos: </label>
            <input type="number" name="Caballos" class="form-control" /><br />

        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcDynamoAWS/Views/Coches/Delete.cshtml
@model MvcDynamoAWS.Models.Coche

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Coche</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdCoche)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdCoche)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Marca)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Marca)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Modelo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Velocidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Velocidad)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MvcDynamoAWS/Views/Coches/Details.cshtml
@model MvcDynamoAWS.Models.Coche

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Coche</h4>
    <hr />
    @if (Model.Motor != null)
    {
        <p>Tipo: @Model.Motor.Tipo</p>
        <p>Caballos: @Model.Motor.Caballos</p>
        <p>Cilindrada: @Model.Motor.Cilindrada</p>
    }
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdCoche)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdCoche)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Marca)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Marca)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Modelo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Velocidad)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Velocidad)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

MvcDynamoAWS/Views/Coches/Index.cshtml
@model IEnumerable<MvcDynamoAWS.Models.Coche>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<p>
    <a asp-action="SearchCoches">Filtrar</a>
</p>
@if (Model != null)
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.IdCoche)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Marca)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Modelo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Velocidad)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.IdCoche)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Marca)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Modelo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Velocidad)
                    </td>
                    <td>
                        <a asp-controller="Coches"
                           asp-action="Delete"
                           asp-route-id="@item.IdCoche">
                            Delete
                        </a>
                        <a asp-controller="Coches"
                           asp-action="Details"
                           asp-route-id="@item.IdCoche">
                            Details
                        </a>

                    </td>
                </tr>
            }
        </tbody>
    </table>

}

MvcDynamoAWS/Views/Coches/SearchCoches.cshtml
@model IEnumerable<MvcDynamoAWS.Models.Coche>

@{
    ViewData["Title"] = "SearchCoches";
}

<h1>SearchCoches</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form method="post">
    <label>Filtrar por marca</label>
    <input type="text" name="marca" />

    <br/>
    <button class="btn btn-info" type="submit">
        Filtrar
    </button>
</form>
@if (Model != null)
{

    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.IdCoche)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Marca)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Modelo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Velocidad)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.IdCoche)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Marca)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Modelo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Velocidad)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                        @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                        @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                    </td>
                </tr>
            }
        </tbody>
    </table>

}

MvcDynamoAWS/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcDynamoAWS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcDynamoAWS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcDynamoAWS</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"
                               asp-area=""
                               asp-controller="Home"
                               asp-action="Privacy">
                                Privacy
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"
                               asp-area=""
                               asp-controller="Coches"
                               asp-action="Index">
                                CochesDynamo
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MvcDynamoAWS - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>